### ISSUE TITLE
This module is re-writing ALLOWED_HOSTS to ['*'] causing major issues

### ISSUE THREAD

**Issue by iMerica** [mozmeao/django-allow-cidr#12]
* Django Allow CIDR version: django-allow-cidr==0.3.1
* Django version: Django==2.2.7 and Django==3 beta
* Python version: 3.8
* Operating System: Alpine

### Description

On certain views, I'm seeing
```
Invalid HTTP_HOST header: '*'. The domain name provided is not valid according to RFC 1034/1035.
``` 

When I print `ALLOWED_HOSTS`, I see `['*']`. Which doesn't actually align with what I actually have in settings.

The error actually occurs when I bust a cache in certain views when calling `django.utils.cache.get_cache_key`.

### What I Did'

I fixed the issue by removing this dependency from my project. Unfortunately, I'll have to find another way to provide Kubernetes health check probes.

**Comment by iMerica** [comment]
If anyone is having the same issue, I published a package that solves the problem in a different way

https://github.com/iMerica/django-allow-healthchecks

**Comment by pmac** [comment]
It sets `ALLOWED_HOSTS` to `['*']` in order to bypass the normal Django HOST header check so that the CIDR values can be checked. I don't see how your package would work since the HOST header checks normally occur before the middleware is processed. Perhaps that has changed in more recent versions of Django.

Regardless this is working as intended. The error you mention is being thrown because requests are sending a host header of `'*'` which is indeed not valid and should have nothing to do with this package.

**Comment by nikolaik** [comment]
If you are interested there is a solution for the issue with kubernetes readiness probes sending HTTP requests with no host header to the pod IP. This solution does not require any application level changes.

We use helm and the a deployment.yaml similar to:
```yaml
....
readinessProbe:
  httpGet:
    path: /healthz
    port: {{ .Values.port }}
    httpHeaders:
      - name: host
        value: {{ (split "," .Values.allowedHosts)._0 }}
```
which could translate into:
```yaml
....
readinessProbe:
  httpGet:
    path: /healthz
    port: 80
    httpHeaders:
      - name: host
        value: example.com
```
meaning the probes will raise [`DisallowedHost`](https://github.com/django/django/blob/e348ab0d4382b0d7cb0cab9d1261c916c3d0ce6c/django/http/request.py#L137) in django

For reference the [docs on readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request) states:
> If your pod relies on virtual hosts, which is probably the more common case, you should not use host, but rather set the Host header in httpHeaders
